title: ECE521 Inference Algorithms and Machine Learning
description: ECE521 course website
sitename: ECE521
baseurl: '/ece521'
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - contents
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
markdown: kramdown
